### ISSUE TITLE
Complete Software Design Evaluation

### ISSUE THREAD

**Issue by shahzad1999** [oUnknown0/ICT2106_P3-3#19]
Complete software design evaluation part of the report by Thursday night

**Comment by sammtann** [comment]
![Image](https://user-images.githubusercontent.com/45651113/222368113-0a33d25b-19c3-4efb-80b2-9d443a519d02.png)




![Image](https://user-images.githubusercontent.com/45651113/222368627-9e4da59d-022a-4afd-b909-82bdf67dc1b7.png)



![Image](https://user-images.githubusercontent.com/45651113/222368686-560ca594-e5bb-48bb-8815-7c2f0ec1d582.png)
