### ISSUE TITLE
What went wrong

### ISSUE THREAD

**Issue by shahzad1999** [oUnknown0/ICT2106_P3-3#28]
- Use case diagram not very well done, not clear how many transactions
- Some of the diagrams do not have descriptions and hence making it incomplete
- Sequence diagram: user should connect to webserver then goes to controller then to view
- Sequence diagram methods did not match the arrows
- Class diagrams arrow implemented wrongly
- Class diagrams not representing the component diagram well. Some parts from class diagrams missing
- There were some miscommunication between team members resulting in different ways of doing things
-  use case description should not have one or 2 flow of activities

**Comment by shahzad1999** [comment]
Everyone to take note of what went wrong and please add on to the list

**Comment by mrdylanchew** [comment]
- Sequence diagram methods did not follow our class methods
- Typo error on alternate flow for sequence diagram

**Comment by marcusohx** [comment]
- No discription for sequence diagram

**Comment by oUnknown0** [comment]
Github board should be updated consistently and to take ownership of the tasks being assigned
