### ISSUE TITLE
Implement project logging feature

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#32]

**Comment by mrdylanchew** [comment]
![Image](https://user-images.githubusercontent.com/94624889/227133893-8516e0e2-676b-4167-8df7-d4c4c0963c9b.png)

**Comment by mrdylanchew** [comment]
![Image](https://user-images.githubusercontent.com/94624889/229067602-6b981742-f957-4fe2-8513-95401fbd0a0b.png)
