### ISSUE TITLE
Implement pin project and tagging feature

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#34]

**Comment by tzw99556** [comment]
Trying to implement status column into the database.

**Comment by tzw99556** [comment]
Still having trouble to implement the status column in database will do more in depth research on it.

**Comment by tzw99556** [comment]
Pin Project Function is completed tagging in progress

**Comment by tzw99556** [comment]
Pin Project Feature:

![Image](https://user-images.githubusercontent.com/90042944/225532839-4042603c-607f-4af7-96cb-922a3a903408.png)

**Comment by tzw99556** [comment]
Tagging feature still in progress will try to work on it

**Comment by tzw99556** [comment]
![Image](https://user-images.githubusercontent.com/90042944/228759430-8100953c-c382-491d-90f4-6168bd077c9b.png)

improved final pin project UI
