### ISSUE TITLE
What can be Improved

### ISSUE THREAD

**Issue by shahzad1999** [oUnknown0/ICT2106_P3-3#35]
- Communication amongst team members to be improved, ensure everyone on the same page.
- Brush up class, sequence and component diagrams
- Split the tasks properly amongst members.
- Everyone to take ownership of their tasks/feature
- Be more consistent in updating project board
- Be more thorough for D2 report such that every diagram is explained properly
- Explicitly describe the flow of activities clearly with 2 or more transaction.

**Comment by shahzad1999** [comment]
Everyone to take note and consciously work commit to these improvements for D2

**Comment by mrdylanchew** [comment]
Improving our github project board management:

-  Have to enforce ownership on issues/tasks
- The person that is assigned have to update their progress
- Future issues created will do labels for tagging for easier management

**Comment by sammtann** [comment]
report: mitigate risk
- not write about what was discussed during the client meeting but focus more on when planning out the features, what are the possible risks to bring up to the client

**Comment by tzw99556** [comment]
Sequence diagram 
- Make sure there is description to explain every feature with the aid of Sequence Diagram

**Comment by marcusohx** [comment]
Class diagram

-improve class diagram and make changes accordingly

**Comment by oUnknown0** [comment]
Reflection should be about my contribution and what I learnt.
