### ISSUE TITLE
Discuss on class ownership

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#36]

**Comment by tzw99556** [comment]
- Doing Pinning feature and tagging feature

**Comment by sammtann** [comment]
did search feature (shown in d1), will help out for other features if needed

**Comment by shahzad1999** [comment]
Doing the export report with different file types feature and will start taking ownership for classes associated with it

**Comment by oUnknown0** [comment]
Ownership over PinProject class

**Comment by mrdylanchew** [comment]
My part is to focus on the logging feature of projects. So any actions such as update, create, delete to the project details will be logged and recorded to a repository to display user actions for Admin users
