### ISSUE TITLE
Refine the class diagram

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#37]

**Comment by shahzad1999** [comment]
Currently working on refining for the export file related classes. Intending to add a pattern

**Comment by tzw99556** [comment]
trying to map out pin project and tagging function in the class diagram.

**Comment by shahzad1999** [comment]
Class diagram refinement going well, added abstract factory pattern

**Comment by mrdylanchew** [comment]
23/3/2023 Updated class diagram that implements observer pattern:



![Image](https://user-images.githubusercontent.com/94624889/227133697-754fd733-c9b5-4ddc-8091-f3605e881da2.png)


Also updated ViewManagement class to follow Single-Responsibility principle:



![Image](https://user-images.githubusercontent.com/94624889/227133815-c6cbd5cd-1a9b-4332-9d6b-d1c247371640.png)

**Comment by shahzad1999** [comment]
Class diagram now implements both the abstract factory pattern and conforms to the Dependency inversion Principle. Need to screenshot and update diagram in the report.

![Image](https://user-images.githubusercontent.com/97570486/227136583-84b88ba0-dca3-406b-83e5-b05b916e2109.png)

**Comment by oUnknown0** [comment]
Class diagram refined and updated the functions within the each classes.

**Comment by shahzad1999** [comment]
Class diagram has been fully refined. It can be found here : https://lucid.app/lucidchart/acde21f8-a6cf-47f1-b6f8-3b369c4e84f5/edit?invitationId=inv_31a9ae11-6f17-4310-9d44-84df10935dbc&page=MXBF4Wmgsogg#
