### ISSUE TITLE
Refine component diagram

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#38]

**Comment by shahzad1999** [comment]
In the Midst of refining class diagram, will update component diagram if necessary

**Comment by shahzad1999** [comment]
Component diagram still not done. Finalising class diagram first

**Comment by shahzad1999** [comment]
Planning to meet with the team this sunday to finish up the component diagram since class diagram is already done.

**Comment by shahzad1999** [comment]
Consulting prof indri to refine component diagram. team is unsure on how to sync the component with class diagram. Looking to refine after.

**Comment by mrdylanchew** [comment]
![Image](https://user-images.githubusercontent.com/94624889/229067457-e67b6d89-f23a-4cb4-ba1a-b145b0cd69f1.png)

**Comment by oUnknown0** [comment]
Component diagram done

Final output of the team component diagram

![Image](https://user-images.githubusercontent.com/33472641/229087978-217d7a42-b128-4cc9-89fe-1d8ee42f086a.png)

Final output of the integrated component diagram (module level)

![Image](https://user-images.githubusercontent.com/33472641/229088033-9fac882b-5d24-46ed-9683-c3eac11051d8.png)

Final output of the integrated component diagram (class level)

![Image](https://user-images.githubusercontent.com/33472641/229088610-82dc61c1-fe13-4fea-b2f6-b512942ab28a.png)

For higher res images, refer to 
https://lucid.app/lucidchart/8879e821-9161-46bb-9b03-229de3d6ce87/edit?beaconFlowId=280C130915392A91&invitationId=inv_3427bde8-0edc-43e7-9689-3e4f79b9c37e&page=TDqK2q~QvLwJ#
