### ISSUE TITLE
Questions for Deliverable 2

### ISSUE THREAD

**Issue by shahzad1999** [oUnknown0/ICT2106_P3-3#42]
- When is our next deadline?
- Who is handling which features?
- Is our new feature (logging) feasible and able to implement to the rest?
- How often are we intending to do the project together as a team?

**Comment by shahzad1999** [comment]
Add more questions as time goes on

**Comment by marcusohx** [comment]
Discuss on which SOLID principles to be adopted for D2

**Comment by tzw99556** [comment]
@marcusohx  we have decided to use single responsibility and dependency inversion principle for D2
