### ISSUE TITLE
Check that all features are completed

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#43]

**Comment by tzw99556** [comment]
feature for pinning is still in progress

**Comment by tzw99556** [comment]
update: feature for pinning is still in progress

**Comment by shahzad1999** [comment]
Exporting file as different formats still in progress. Working on it.

**Comment by mrdylanchew** [comment]
Update: still planning and creating classes like LoggingRepo, and the logging method to record user actions

**Comment by tzw99556** [comment]
Update: Pin Project Function is completed

**Comment by shahzad1999** [comment]
update: Export file feature still in progress

**Comment by shahzad1999** [comment]
Feature is almost done. Need help from @oUnknown0 to ensure it is correct

**Comment by mrdylanchew** [comment]
loggign feature: created and populated data into the YouthAction.db 

the logging table will pull and read data from the db. it is not fully implemented to add logging data dynamically from all user actions performed

**Comment by shahzad1999** [comment]
Export feature is completed. Able to export report out as .pdf, .docx and .xls

**Comment by oUnknown0** [comment]
Archived feature is completed
