### ISSUE TITLE
Improve class diagram

### ISSUE THREAD

**Issue by marcusohx** [oUnknown0/ICT2106_P3-3#45]

**Comment by mrdylanchew** [comment]
- We will change some methods to be public
- finalize method names according to the code
- improve the arrows and connections between classes whether entity, boundary or interface

**Comment by mrdylanchew** [comment]
23/3/2023 Updated class diagram that implements observer pattern:



![Image](https://user-images.githubusercontent.com/94624889/227133697-754fd733-c9b5-4ddc-8091-f3605e881da2.png)


Also updated ViewManagement class to follow Single-Responsibility principle:



![Image](https://user-images.githubusercontent.com/94624889/227133815-c6cbd5cd-1a9b-4332-9d6b-d1c247371640.png)

**Comment by shahzad1999** [comment]
class diagram is completed. 



![Image](https://user-images.githubusercontent.com/97570486/227140887-1a856381-682b-426b-9bef-b43eca7da55b.png)

**Comment by oUnknown0** [comment]
Class diagram completed and final outcome

![Image](https://user-images.githubusercontent.com/33472641/229086953-d8e490ee-3720-4d43-b5bb-35dfbe7c097e.png)

For higher res image refer to 
https://lucid.app/lucidchart/8879e821-9161-46bb-9b03-229de3d6ce87/edit?beaconFlowId=280C130915392A91&invitationId=inv_3427bde8-0edc-43e7-9689-3e4f79b9c37e&page=TDqK2q~QvLwJ#
