### ISSUE TITLE
Discuss on class diagram design pattern implementation

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#47]

**Comment by oUnknown0** [comment]
Designed a draft for bridge design pattern. 

Reason for adding bridge design pattern to the report export features is due to the fact that Bridge design pattern decouples the implementation from the abstract class. In this case the abstract class is the report which contains report generation methods. The implementation is the export report feature which allows the export of different file types such as XLS, DOCS and PDF

**Comment by shahzad1999** [comment]
![Image](https://user-images.githubusercontent.com/97570486/225533932-033b842b-c359-4302-aadf-5c672fd96c28.png)

**Comment by shahzad1999** [comment]
Converted the classes that are related to report generation using the abstract factory pattern where. The types of report that can be created are .pdf, .docx and .xls type reports

**Comment by tzw99556** [comment]
to add on what @shahzad1999  has posted for the image , .pdf .docs. xls will communicate with each respective file format factories.

**Comment by sammtann** [comment]
proposed facade design pattern, where i combine some methods together in one facade class, not sure if will go ahead with the coding

![Image](https://user-images.githubusercontent.com/45651113/225537588-257cc499-54ab-42c5-9339-63418c9a7da8.png)
