### ISSUE TITLE
Discuss on class diagram design principles

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#48]

**Comment by shahzad1999** [comment]
As discussed, the first principle that we will follow is the Single responsibility principle. Second principle is the interface segregation principle

**Comment by tzw99556** [comment]
As discussed, the principle which will best fit our class diagram which is dependency inversion and single responsibility principle. we have also decided that interface segregation principle may not best fit our class diagram.

**Comment by mrdylanchew** [comment]
Single Responsibility:

before
![Image](https://user-images.githubusercontent.com/94624889/228760016-7ccf4762-43fb-4c55-b5fc-d3acd35f62ef.png)


after
![Image](https://user-images.githubusercontent.com/94624889/228760287-025e1d61-92bd-4062-8526-ad94462b2775.png)
