### ISSUE TITLE
Decide on module 2 functions to be completed with the other group sharing the same module

### ISSUE THREAD

**Issue by oUnknown0** [oUnknown0/ICT2106_P3-3#5]

**Comment by mrdylanchew** [comment]
Proposed Features:

1. Adding Members into Project Role
2. Pin function allowing users to pin important projects on top of the website
3. Store projects that have ended in archive/history tab
4. Project sorting functions (By date, member and etc)
5. Allow client to download project description exported via pdf
6. Generate reports for project progress and people managing the project
7. Project category filters
8. Manage a list of projects (Add, update, delete, view)
9. Search function to search the projects
