### ISSUE TITLE
Consult prof regarding component diagram

### ISSUE THREAD

**Issue by shahzad1999** [oUnknown0/ICT2106_P3-3#50]
Consulting prof indri regarding the syncing of class and component diagram later at 4pm after project presentation.

**Comment by oUnknown0** [comment]
Component diagram looks alright but bridge pattern is not necessary as it is redundant. There is already a abstract factory pattern to handle the report

**Comment by shahzad1999** [comment]
Component diagram has been updated according to the consultation with prof. Class diagram and component diagram are in sync..

Thanks for the help everyone. @oUnknown0 @marcusohx @tzw99556 @mrdylanchew @sammtann 

Here is the image: 

![Image](https://user-images.githubusercontent.com/97570486/229069467-568ac545-f628-4076-9c3c-564982084e10.png)
